### ISSUE TITLE
Have you tried better VDM model for inversion?

### ISSUE THREAD

**Issue by Tonniia** [MCG-NJU/BIVDiff#3]
Hi, I am interested in your idea of VDM and IDM mixed inversion. I'm confused about why pure VDM inversion (alpha=0) generated inconsistent video in Fig.10. Maybe that is because VidRD is not powerful enough?

**Comment by ShiFengyuan1999** [comment]
Hi @Sutongtong233, the main cause is that alpha is too slow instead of VDMs. When alpha is 0, there are no image components to be temporally smoothed. The videos generated by IDM are inverted to pure noise and then denoised to videos. When alpha is 0, the inversion and denoising process uses the same VDM, so the final video is the same as the temporally inconsistent video generated by IDM (actually near the same since the inversion process has some error). Increasing alpha leads to temporal consistent videos. 

We tried two open-sourced video diffusion models (VidRD and ZeroScope). You can use better VDM for further improvements.

**Comment by Tonniia** [comment]
thanks for the response~
